export const ERRORS = {
    RA_DUPLICATED:'RA_DUPLICATED',
    EMAIL_DUPLICATED:'EMAIL_DUPLICATED',
    CPF_DUPLICATED:'CPF_DUPLICATED',
    STUDENT_NOT_FOUND:'STUDENT_NOT_FOUND',
    STUDENT_CREATION_ERROR:'STUDENT_CREATION_ERROR',
    INTERNAL_SERVER_ERROR:'INTERNAL_SERVER_ERROR',
}