version: '3.8'

services:
  frontend:
    container_name: frontend-vue
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./.env:/app/../.env:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - maisaedu-network

  backend:
    container_name: backend-node
    build: ./backend
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - db
    restart: unless-stopped
    command: sh -c "npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && npm run start"
    networks:
      - maisaedu-network

  db:
    container_name: db-mysql
    image: mysql:8
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - maisaedu-network

networks:
  maisaedu-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
